/**
 * Live Events Scraper - fetches current events via web search
 * This provides real-time events rather than static curated data
 */
export class LiveEventsScraper {
  constructor() {
    this.name = 'Live Singapore Events';
  }

  async scrape(options = {}) {
    console.log('Fetching live events from web sources...');
    console.log('(This requires internet access and web search capability)\n');

    // This scraper is designed to work with the CLI's web search integration
    // When run standalone, it returns instructions for manual lookup

    const currentDate = new Date();
    const weekendStart = this.getNextWeekend(currentDate);

    return [
      {
        source: 'Live Events Info',
        title: 'How to get live Singapore events',
        description: `For real-time weekend events, visit these sites directly or use the web search feature. Current date: ${currentDate.toDateString()}`,
        category: 'Info',
        location: 'Singapore',
        date: `Weekend of ${weekendStart.toDateString()}`,
        url: 'https://www.timeout.com/singapore/things-to-do/things-to-do-in-singapore-this-weekend',
        price: 'Free to browse',
      },
      {
        source: 'Recommended Sources',
        title: 'TimeOut Singapore - This Weekend',
        description: 'Curated list of the best things to do in Singapore this weekend including events, exhibitions, and activities.',
        category: 'Events Guide',
        location: 'Singapore',
        date: 'Updated weekly',
        url: 'https://www.timeout.com/singapore/things-to-do/things-to-do-in-singapore-this-weekend',
        price: 'Varies',
      },
      {
        source: 'Recommended Sources',
        title: 'The Smart Local - Weekend Guide',
        description: 'Local perspective on the best things to do this weekend in Singapore with insider tips.',
        category: 'Events Guide',
        location: 'Singapore',
        date: 'Updated weekly',
        url: 'https://thesmartlocal.com/read/things-to-do-this-weekend-singapore/',
        price: 'Varies',
      },
      {
        source: 'Recommended Sources',
        title: 'Little Day Out - Family Events',
        description: 'Family-friendly activities and events happening this weekend in Singapore.',
        category: 'Family Events',
        location: 'Singapore',
        date: 'Updated weekly',
        url: 'https://www.littledayout.com/things-to-do-this-weekend-in-singapore/',
        price: 'Varies',
      },
      {
        source: 'Recommended Sources',
        title: 'Vogue Singapore - Weekend Guide',
        description: 'Lifestyle and cultural events curated by Vogue Singapore.',
        category: 'Lifestyle',
        location: 'Singapore',
        date: 'Updated weekly',
        url: 'https://vogue.sg/what-to-do-this-weekend-singapore-2026/',
        price: 'Varies',
      },
      {
        source: 'Recommended Sources',
        title: 'AllEvents.in Singapore',
        description: 'Comprehensive event listings for Singapore including concerts, workshops, and meetups.',
        category: 'All Events',
        location: 'Singapore',
        date: 'Real-time',
        url: 'https://allevents.in/singapore/this-weekend',
        price: 'Varies',
      },
    ];
  }

  getNextWeekend(date) {
    const day = date.getDay();
    const daysUntilSaturday = (6 - day + 7) % 7 || 7;
    const saturday = new Date(date);
    saturday.setDate(date.getDate() + (day === 0 ? 6 : day === 6 ? 0 : daysUntilSaturday));
    return saturday;
  }
}

// Current events data that can be updated
// This is populated from web search results
export const CURRENT_WEEKEND_EVENTS = [
  {
    source: 'TimeOut Singapore',
    title: 'Lunar New Year Festivities 2026',
    description: 'Celebrate the Year of the Snake with lion dances, Fortune God greetings, games and crafts at various heartland locations.',
    category: 'Festival',
    location: 'Woodlands North Plaza, Fajar Shopping Centre, Sembawang Mart, Taman Jurong',
    date: 'Jan 31 - Feb 1, 2026, 11am-2pm',
    url: 'https://www.timeout.com/singapore/things-to-do/things-to-do-in-singapore-this-weekend',
    price: 'Free',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Dahlia Dreams at Gardens by the Bay',
    description: 'Eight majestic life-sized horse lanterns handcrafted by Chinese artisans using Tang Dynasty techniques, amid plum blossoms, orchids, chrysanthemums and bamboo.',
    category: 'Exhibition',
    location: 'Flower Dome, Gardens by the Bay',
    date: 'Jan 16 - Mar 1, 2026',
    url: 'https://www.gardensbythebay.com.sg/',
    price: 'S$20-53',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Ren Faire SG: The Origin',
    description: 'First Renaissance fair in Singapore with live action role-playing, musical performances, quests, marketplace with 100+ vendors, food and games.',
    category: 'Festival',
    location: 'Fort Canning Park',
    date: 'Jan 31 - Feb 1, 2026',
    url: 'https://www.renfairesg.com/',
    price: 'Check website',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Gimme Gimme Disco - ABBA Dance Party',
    description: 'An ABBA-inspired disco dance party. Get ready to dance to all your favorite ABBA hits!',
    category: 'Nightlife',
    location: 'Zouk Singapore',
    date: 'Sat Jan 31, 2026, 6:30 PM',
    url: 'https://www.zoukclub.com/',
    price: 'Check website',
  },
  {
    source: 'TimeOut Singapore',
    title: 'SingaporeBrides Wedding Fair 2026',
    description: 'The premier wedding fair in Singapore featuring vendors, exhibitions, and deals for couples planning their wedding.',
    category: 'Exhibition',
    location: 'Sands Expo & Convention Centre',
    date: 'Sat Jan 31, 2026, 12:00 PM',
    url: 'https://www.singaporebrides.com/',
    price: 'Free entry',
  },
  {
    source: 'TimeOut Singapore',
    title: 'The Dempsey Palate Pop-up',
    description: 'Outdoor pop-up featuring live music by Ann Siang Sounds and bites from Burnt Ends, Margarita\'s, Park Bench Deli x The Pantry, and RedDot BrewHouse.',
    category: 'Food & Drink',
    location: 'Dempsey Hill',
    date: 'This weekend',
    url: 'https://www.dempseyhill.com/',
    price: 'Varies',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Light to Night Festival 2026',
    description: '10th edition with theme "The Power in Us" - light projections on Civic District buildings, interactive art installations, free and ticketed programmes.',
    category: 'Art & Culture',
    location: 'Civic District',
    date: 'Ongoing January 2026',
    url: 'https://www.nationalgallery.sg/lighttonight',
    price: 'Free (some events ticketed)',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Demon Slayer: Kimetsu no Yaiba Exhibition',
    description: 'The largest Demon Slayer exhibition arrives in Singapore for the first time. A must-visit for anime fans!',
    category: 'Exhibition',
    location: 'Singapore Sports Hub Library',
    date: 'Jan 24 - Mar 15, 2026',
    url: 'https://www.sportshub.com.sg/',
    price: 'Check website',
  },
  {
    source: 'TimeOut Singapore',
    title: 'Garden of Senses: A Tea Reverie',
    description: 'Exhibition exploring tea as a deeply human ritual through the senses.',
    category: 'Exhibition',
    location: 'Asian Civilisations Museum',
    date: 'Jan 28 - Jun 7, 2026',
    url: 'https://www.nhb.gov.sg/acm/',
    price: 'Check website',
  },
  {
    source: 'TimeOut Singapore',
    title: 'COMMA 2026: Softer Systems',
    description: 'Arts festival featuring live performances, art exhibitions and participatory experiences.',
    category: 'Art & Culture',
    location: '*Scape Somerset Belt',
    date: 'Jan 16-31, 2026',
    url: 'https://www.scape.sg/',
    price: 'Free',
  },
  // February 2026 Events
  {
    source: 'Songkick',
    title: 'Westlife Concert',
    description: 'Irish pop band Westlife on their Asia Tour - one of only three stops in Asia!',
    category: 'Concert',
    location: 'Arena @ EXPO, Singapore Expo',
    date: 'Feb 3, 2026',
    url: 'https://www.songkick.com/metro-areas/32258-singapore-singapore/2026',
    price: 'From S$128',
  },
  {
    source: 'Songkick',
    title: 'Michael Learns To Rock (MLTR)',
    description: 'Danish soft rock band performing their greatest hits including "Take Me To Your Heart".',
    category: 'Concert',
    location: 'The Star Theatre',
    date: 'Feb 5, 2026',
    url: 'https://www.songkick.com/metro-areas/32258-singapore-singapore/2026',
    price: 'Check website',
  },
  {
    source: 'Harpers Bazaar',
    title: 'Cirque du Soleil: KOOZA',
    description: 'Cirque du Soleil returns after 7 years with KOOZA - gravity-defying acrobatics, tightrope walkers, contortionists under the iconic Big Top.',
    category: 'Show',
    location: 'Bayfront Event Space',
    date: 'Feb 6-22, 2026',
    url: 'https://www.cirquedusoleil.com/',
    price: 'From S$88',
  },
  {
    source: 'Songkick',
    title: 'Mei Semones World Tour',
    description: 'One of only two Southeast Asian stops on her World Tour.',
    category: 'Concert',
    location: 'Pasir Panjang Power Station',
    date: 'Feb 6, 2026',
    url: 'https://www.songkick.com/metro-areas/32258-singapore-singapore/2026',
    price: 'Check website',
  },
  {
    source: 'Songkick',
    title: 'Bryan Adams: Roll With the Punches Tour',
    description: 'Rock legend Bryan Adams performing hits like "Summer of 69" and "Everything I Do".',
    category: 'Concert',
    location: 'Arena @ EXPO, Singapore Expo',
    date: 'Feb 7, 2026',
    url: 'https://www.songkick.com/metro-areas/32258-singapore-singapore/2026',
    price: 'From S$148',
  },
  {
    source: 'Singapore Airshow',
    title: 'Singapore Airshow 2026',
    description: 'Asia\'s leading aerospace exhibition with aerial displays, aircraft showcase, and aviation technology. Public days Feb 7-8.',
    category: 'Exhibition',
    location: 'Changi Exhibition Centre',
    date: 'Feb 3-8, 2026 (Public: Feb 7-8)',
    url: 'https://www.singaporeairshow.com/',
    price: 'S$19-39',
  },
  {
    source: 'Gardens by the Bay',
    title: 'River Hongbao 2026',
    description: 'Annual CNY celebration with elaborate lantern displays, cultural performances, festive food stalls, and family activities.',
    category: 'Festival',
    location: 'Gardens by the Bay',
    date: 'Feb 15-24, 2026, 6:30pm-10:30pm',
    url: 'https://www.riverhongbao.sg/',
    price: 'Free',
  },
  {
    source: 'Chingay',
    title: 'Chingay Parade 2026',
    description: 'Iconic Singapore parade with massive floats, dazzling costumes, and multicultural performances celebrating unity and diversity.',
    category: 'Festival',
    location: 'F1 Pit Building',
    date: 'Feb 27-28, 2026, 8pm',
    url: 'https://www.chingay.gov.sg/',
    price: 'S$20-60',
  },
  {
    source: 'Songkick',
    title: 'David Tao Concert',
    description: 'Taiwanese R&B and rock legend performing his greatest hits with interactive segments.',
    category: 'Concert',
    location: 'Singapore Indoor Stadium',
    date: 'Feb 28, 2026',
    url: 'https://www.songkick.com/metro-areas/32258-singapore-singapore/2026',
    price: 'Check website',
  },
  {
    source: 'National Gallery Singapore',
    title: 'Impressionism: Masterpieces from MFA Boston',
    description: 'Landmark exhibition featuring iconic works by Renoir, Monet, Manet, Cézanne, and Degas - never before exhibited in Singapore.',
    category: 'Exhibition',
    location: 'National Gallery Singapore',
    date: 'Feb 2026 onwards',
    url: 'https://www.nationalgallery.sg/',
    price: 'S$20-25',
  },
  {
    source: 'Trip.com',
    title: 'Harry Potter: Visions of Magic',
    description: 'Interactive wizarding world experience featuring immersive environments like the Room of Requirement and Newt\'s Menagerie.',
    category: 'Exhibition',
    location: 'Resorts World Sentosa',
    date: 'Ongoing 2026',
    url: 'https://www.rwsentosa.com/',
    price: 'From S$42',
  },
  // More ongoing events
  {
    source: 'ArtScience Museum',
    title: 'Future World: Where Art Meets Science',
    description: 'Permanent interactive digital art exhibition by teamLab. Immersive installations that respond to your presence.',
    category: 'Exhibition',
    location: 'ArtScience Museum, Marina Bay Sands',
    date: 'Ongoing',
    url: 'https://www.marinabaysands.com/museum/exhibitions/future-world.html',
    price: 'S$17-26',
  },
  {
    source: 'Klook',
    title: 'S.E.A. Aquarium',
    description: 'One of the world\'s largest aquariums with over 100,000 marine animals across 50 habitats.',
    category: 'Attraction',
    location: 'Resorts World Sentosa',
    date: 'Daily, 10am-5pm',
    url: 'https://www.rwsentosa.com/en/attractions/sea-aquarium',
    price: 'S$41-46',
  },
  {
    source: 'Mandai Wildlife',
    title: 'Bird Paradise',
    description: 'Asia\'s largest bird park with over 3,500 birds across 400 species in immersive walk-through aviaries.',
    category: 'Attraction',
    location: 'Mandai Wildlife Reserve',
    date: 'Daily, 9am-6pm',
    url: 'https://www.mandai.com/en/bird-paradise.html',
    price: 'S$48',
  },
  {
    source: 'Urban List',
    title: 'Spectra Light & Water Show',
    description: 'Free nightly spectacular with dancing fountains, lasers, and music at Marina Bay Sands.',
    category: 'Entertainment',
    location: 'Marina Bay Sands Event Plaza',
    date: 'Nightly 8pm & 9pm (Fri-Sat +10pm)',
    url: 'https://www.marinabaysands.com/entertainment/spectra.html',
    price: 'Free',
  },
  {
    source: 'Jewel Changi',
    title: 'Rain Vortex & Canopy Park',
    description: 'World\'s tallest indoor waterfall plus sky nets, hedge maze, and bouncing nets at Jewel Changi Airport.',
    category: 'Attraction',
    location: 'Jewel Changi Airport',
    date: 'Daily',
    url: 'https://www.jewelchangiairport.com/',
    price: 'Free (Canopy Park S$24-54)',
  },
];
